# .github/workflows/on-dispatch.yml
name: Run E2E Tests on Dispatch

on:
  repository_dispatch:
    types: [run-e2e]

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout E2E repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run E2E tests
        run: npm run test:e2e
